### ISSUE TITLE
look into substituting infura http provider with incubed for ethereum blockchain

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1857]
Any http requests which currently being served by infura can potentially be served via incubed in a trestles manner.

let's look into and try to integrate it as well.

reference links:

- intro https://youtu.be/Z3sa0DUsZjA
- docs https://slock.it/incubed/

**Comment by omurovch** [comment]
Integrated incubed client to ethereum-kit. Implementation is pushed to branch in3 (https://github.com/horizontalsystems/ethereum-kit-android/tree/in3). However during testing a problem was encountered. Created issue for this in in3-c repo, see https://github.com/slockit/in3-c/issues/11. Further testing and integration to ethereum-kit is postponed till this problem is solved.
