### ISSUE TITLE
Handle Case When fingerprints cannot be recognized

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2101]
Ex. To show alert as on iOS (see below) 

"Fingerprint Not Recognized. Please enter your password" 

![2020-04-15 11 40 51](https://user-images.githubusercontent.com/22589457/79302372-00540f00-7f0e-11ea-98f3-cfd833234018.jpg)

**Comment by rafaelekol** [comment]
https://medium.com/appnroll-publication/what-is-new-in-android-p-biometricprompt-d4fc85e55608

**Comment by TalgatNurdinov** [comment]
<img width="1199" alt="Screen Shot 2020-04-20 at 12 26 07 PM" src="https://user-images.githubusercontent.com/42367908/79720427-5e179b00-8302-11ea-874c-88cc09917d38.png">

**Comment by Dianaaiym** [comment]
the color of a button 'Cancel' will be 'Jacob' as on previous screen

**Comment by rafaelekol** [comment]
We  are using system popup dialog to scan fingerprint. We are not controlling its colors.

**Comment by rafaelekol** [comment]
In search how to customize FingerPrint Dialog, I went through Android documentation on Biometric prompt. Due to variety Android devices and different scanners like fingerprint, face recognition and even iris scanner, Google provides with single solution as Biometric Prompt. In documentation they suggest to use system dialog. Here is what they say:
> This system-provided dialog is consistent across the apps that use it, creating a more trustworthy user experience. 
https://developer.android.com/training/sign-in/biometric-auth#display-login-prompt

I think we should stick with system-provided dialog, without customization.
