### ISSUE TITLE
Balance tab animation refactoring

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/unstoppable-wallet-android#2104]
I found good [example of RecyclerView usage by Google](https://github.com/google/iosched)
They use standard animation TransitionManager, when item is expanded or collapsed they trigger Autotransition(that consist from Fade out Fade In and Changebounds animations). I played with code tried to remove Fade out Fade In, leaving only Changebounds. But then there I can see overlaping bottom cells during animations.
Also in this code I saw good example of View Binding usage. We can use this part in our code.

**Comment by abdrasulov** [comment]
I've checked other possible solutions. We can use the method described here https://stackoverflow.com/a/13381228/1073184.

I discussed it with @rafaelekol. It turned out that we had a similar solution before. It had an issue with not fully expanding the balance cell in some cases. Since the current implementation works without any issues, we decided to leave it.
