### ISSUE TITLE
For backing up wallet in 2 occasions the app did not accept the entered words , although it was  written 100% correctly. 

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2347]
Feedback
"I created a Standard Wallet then I tried to delete it. In order to delete it, the user has to back it up first. When backing up, as I wrote above, the 12 (24) words phrase is displayed. After selecting "Backup", in order to delete the wallet, the user is requested to insert two random (actually not random; details below) words of the seed phrase. I also managed to delete multiple wallets. However, a day later I repeated this test and in 2 occasions the app did not accept the words written by me, although I am 100% I wrote them correctly. "

**Comment by abdrasulov** [comment]
The issue is not reproducable. I've tried to check in different states, when both Standard Wallet and Binance Wallet are created, when only one of them is created, when also EOS Wallet is restored. The behaviour is as expected. In all of these cases I could successfully back up words. Also I checked the source code. I didn't find any place that may potentially cause this issue.
