### ISSUE TITLE
Weird animation after changing language

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2420]
We can reproduce it switching between languages.

Sometimes the theme toggle button is triggered after switching language

reproduced on samsung A6 (Android 10)

**Comment by Dianaaiym** [comment]
![IMG_5105](https://user-images.githubusercontent.com/22589457/87298289-c3f37780-c52b-11ea-8357-7ebbffc36a11.gif)

**Comment by rafaelekol** [comment]
What is the device name?

**Comment by Dianaaiym** [comment]
> What is the device name?

Samsung A6, Android 10

**Comment by abdrasulov** [comment]
This is the initial state of the view. When the language is changed the app restarts itself. First, it shows the view as is. Then it sets the appropriate values. Setting the values via `setValue` instead of `postValue` in the ViewModel resolves it. But we cannot use the setValue all time since the method potentially can be triggered in non-main thread.

We decided to postpone it as of now, We'll check for other solutions.

**Comment by abdrasulov** [comment]
There will be support for in-app languages in Android 13 https://developer.android.com/about/versions/13/features/app-languages. Let's check it when it is released
