### ISSUE TITLE
Add famous and widely used world currencies in Base currencies.

### ISSUE THREAD

**Issue by wolfenix** [horizontalsystems/unstoppable-wallet-android#2644]
Kindly Add the known and widely used base currency to the app like : -

1. INR
2. AUD
3. CNY
4. RUB
5. CAD

etc...

**Comment by esengulov** [comment]
> Kindly Add the known and widely used base currency to the app like : -
> 
> 1. INR
> 2. AUD
> 3. CNY
> 4. RUB
> 5. CAD
> 
> etc...

At one point wallet already listed above fiat currencies, we had to remove them as exchange rates for some currencies turned out to be unreliable (diverging more than 2% for some cryptocurrencies). 

As a result we decided to remove them as it can potentially cause undesired behaviors when using the app. For instance, a user may end up sending more than intended amount.

**Comment by wolfenix** [comment]
Ohhhh damnn... this is actually a deep matter, i didn't thought of that!
well, Np mate, do what's best for the wallet.
