### ISSUE TITLE
Mnemonic phase input does not validate the checksum. Potential for loss of funds.

### ISSUE THREAD

**Issue by gmale** [horizontalsystems/unstoppable-wallet-android#2830]
When a user inputs their mnemonic phrase, the checksum is not verified. This could potentially allow invalid phrases (such as ones where the user inverts the seed words) or additional white space to be accepted. That could result in users creating addresses that cannot be restored once these bugs are fixed and thereby result in a loss of funds.

Solution: verify the [checksum](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#user-content-generating_the_mnemonic) per BIP-39 or use a[ library that has this built in](https://github.com/zcash/kotlin-bip39). The current library only [validates that the words are included in the wordlist](https://github.com/horizontalsystems/hd-wallet-kit-android/blob/master/src/main/kotlin/io/horizontalsystems/hdwalletkit/Mnemonic.kt#L96-L109).

This impacts all coins in this wallet that use mnemonic phrases, which seems to be everything but EOS.

**Comment by omurovch** [comment]
Hi @gmale,
When user enters mnemonic phrase, words are not being validated against checksum because user may have created mnemonic phrase in a wallet where checksum is not considered. But when generating mnemonic phrase wallet hdwallet-kit does consider checksum (https://github.com/horizontalsystems/hd-wallet-kit-android/blob/41d5525df2ab64bbcd1bb4ac8a0cdb0713193aa7/src/main/kotlin/io/horizontalsystems/hdwalletkit/Mnemonic.kt#L32)

**Comment by omurovch** [comment]
Hi @gmale,

When user enters mnemonic phrase, words are not being validated against checksum because user may have created mnemonic phrase in a wallet where checksum is not considered. But when generating mnemonic phrase wallet hdwallet-kit does consider checksum (https://github.com/horizontalsystems/hd-wallet-kit-android/blob/41d5525df2ab64bbcd1bb4ac8a0cdb0713193aa7/src/main/kotlin/io/horizontalsystems/hdwalletkit/Mnemonic.kt#L32)

**Comment by defuse** [comment]
Here's how loss of funds would reasonably occur due to this:

1. User obtains a valid seed phrase from any wallet
2. User attempts to restore that seed phrase, but makes a mistake (such as swapping two words)
3. User adds funds to that incorrectly-restored wallet
4. User loses access to the wallet app, their funds are now lost unless they can remember *exactly* what mistake they made

I would strongly recommend at least adding a warning interstitial like

```
This is not a valid seed phrase! 
[TRY AGAIN]    [DANGEROUS: continue with invalid seed phrase]
```

if not completely disabling the ability to import an invalid seed phrase.

**Comment by gmale** [comment]
Hi @omurovch!

We've actually had these issues with users where they'd type in their key from a backup but misread it (for instance, reading "chief" but typing "chef" and both are valid seed words) or, more commonly, just mix up the word order. Dangerously, this results in a valid address and the user incorrectly believes that their backup phrase is correct and safe. One time, we worked with a user and entered the seed about a half-dozen times before spotting the mistake!

Also, given the BIP-39 spec, it's quite unlikely that a user would create a mnemonic phrase that is invalid to begin with. It is more likely that they'd copy it down wrong or enter it incorrectly. I agree with @defuse's suggestion of at least warning about that scenario in the UI.

**Comment by defuse** [comment]
There's a corresponding issue in the iOS mnemonic library: https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/2327 (and another one I noticed while reviewing it: https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/2326)

**Comment by omurovch** [comment]
@gmale @defuse actually it does make sense, even though we've never encountered such case. For the most cases validating that words are included in the wordlist was enough, but the cases you've provided are valid cases and should be considered too. Thanks for heads up!

**Comment by Dianaaiym** [comment]
Show error 'Invalid checksum'
