### ISSUE TITLE
Balance tab: Apply changes for sync error

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2857]
- [x] 'Change Source' should be remove for ETH and erc20 tokens
- [x] remove text ('the error text will be...') under title

**Comment by abdrasulov** [comment]
Hi @herou. Here is another issue.

It is related to class SyncErrorDialog. As of now, it takes a `coinName` as one of the parameters. It should be replaced with a Coin object. Then SyncErrorDialog needs to show or hide the button "Change Source" depending on the CoinType. It should be hidden if the type is Ethereum or Erc20. Otherwise, it should be shown.

The second point is to remove the hint text.

**Comment by herou** [comment]
@abdrasulov Please check if this is okay: #2871 Regarding the second point (remove the hint text) which text should be removed? It should be removed only when the coin is Erc20?

**Comment by rafaelekol** [comment]
Remove hint, completely, for all cases.

**Comment by herou** [comment]
@rafaelekol You have it.

**Comment by abdrasulov** [comment]
Hi @herou. I and @rafaelekol discussed it. There is a parameter named `sourceChangeable` for this purpose. I didn't notice it. My mistake. Sorry :) Could you please re-implement it using that parameter? So to hide a button for ETH and ERC20 tokens we need to add both of them to the list in the `BalancePresenter::sourceChangeable()` method.

**Comment by herou** [comment]
@abdrasulov Nevermind, misunderstanding happens.  I hope it is okay now.

**Comment by herou** [comment]
@abdrasulov @rafaelekol Something else to work on?

**Comment by herou** [comment]
@rafaelekol @abdrasulov Close this issue because is merged.
