### ISSUE TITLE
Pin unlock doesn't work sometimes

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#2985]
When the correct pin entered the app sometimes keeps the Unlock Screen opening

**Comment by herou** [comment]
@abdrasulov It happens to me when I type the pin very fast.

**Comment by herou** [comment]
Check out this link: https://drive.google.com/file/d/1VWO3jKobGKFeMufPxpQNcSdYPr22z-YX/view?usp=sharing

**Comment by abdrasulov** [comment]
Thanks for the video, @herou! In this case, I think it's an issue related to the custom keyboard. I caught this behavior when the last 6th number is also entered.

**Comment by tmedetbekov** [comment]
Fixed by this PR [2985](https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2985)

**Comment by tmedetbekov** [comment]
This issue reproduced when I enabled the "Don't keep activities" menu on the Developer options and opened the locked screen from the background. There was a custom flag for navigation logic which was not restorable by system. Fixed by PR [3090](https://github.com/horizontalsystems/unstoppable-wallet-android/pull/3090)
