### ISSUE TITLE
Failed transactions (Ethereum) should show fail error

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2988]
Currently client shows 'Failed' which is insufficient for a user as it doesn't ay anything in regards to why transaction failed. This is relevant to all transaction, both ERC20 transfers and swaps.

This should be implement after we are done with refactoring Ethereum kit

**Comment by bxxasn** [comment]
The speed of monitoring transactions is very slow. After trading with DAPP, the https://etherscan.io/ You can see that the transaction has been successful. But you can't find this record in the transaction interface of the app

**Comment by omurovch** [comment]
Transaction fail reason is not included in a standard Transaction/Receipt we get from the nodes, because it's not stored in the transaction. It's only possible to obtain that by executing the same TX in the same blockchain state(in a block in which it was executed). This requires an ethereum archive node, which is expensive and there's no service providing it for free.

- Infura provides it for $250/month.
- Alchemy provides for $50/month, but we'll need to implement a Parity Trace parser. And still the error obtained by parity tracing may be different from the one we see on Etherscan

**Comment by omurovch** [comment]
Same issue on ios platform [https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/2430]
