### ISSUE TITLE
Feature Request: Monero

### ISSUE THREAD

**Issue by trymeouteh** [horizontalsystems/unstoppable-wallet-android#3302]
Please support Monero by using the 12 word phrase from the BTC, LTC, ETH wallets

**Comment by fusionneur** [comment]
Subscribed

**Comment by esengulov** [comment]
We have this on a short term task list. As soon as we are done with multi wallet capabilities Monero integration will become a priority for us.

**Comment by nahuhh** [comment]
> We have this on a short term task list. As soon as we are done with multi wallet capabilities Monero integration will become a priority for us.

*rubs hands*
Coming soon? 😋

This will need the ability to connect to your own node.

**Comment by pjakma** [comment]
Yes please!

**Comment by kdejaeger** [comment]
I'd like the following privacy coins to be added : monero, mobilecoin, piratechain (arrr), hush and BEAM.

**Comment by nahuhh** [comment]
> I'd like the following privacy coins to be added : monero, mobilecoin, piratechain (arrr), hush and BEAM.

Imo, from most to least important, for usability 

Monero w ability to use a custom node
Haven
Dero
Arrr
Haven protocol / defi / xassets
Mobilecoin
Beam
Hush

**Comment by trymeouteh** [comment]
Not sure if the devs are struggling to convert 12 and 24 mnemonic phrases into 25 Monero mnemonic phrases but this tool could give an idea how to do this. Just select XMR - Monero and it will show you the XMR Seed words for any BIP39 mnemonic
https://coinomi.github.io/tools/bip39/

**Comment by nahuhh** [comment]
> Not sure if the devs are struggling to convert 12 and 24 mnemonic phrases into 25 Monero mnemonic phrases but this tool could give an idea how to do this. Just select XMR - Monero and it will show you the XMR Seed words for any BIP39 mnemonic
> https://coinomi.github.io/tools/bip39/

If using this method, we should also ensure the ability to backup the 25 word seed is included.

To devs: I think the main necessary feature is to be able to use a local node. 
Would like to see this for other coins, but a good amount of monero users will NOT use a remote node. 

Also, there are *no* monero wallets in f-droid official repo. I think it's important that we have one, and would be nice for unstoppable to be the first.

**Comment by hexchills** [comment]
> > Not sure if the devs are struggling to convert 12 and 24 mnemonic phrases into 25 Monero mnemonic phrases but this tool could give an idea how to do this. Just select XMR - Monero and it will show you the XMR Seed words for any BIP39 mnemonic
> > https://coinomi.github.io/tools/bip39/
> 
> If using this method, we should also ensure the ability to backup the 25 word seed is included.
> 
> To devs: I think the main necessary feature is to be able to use a local node. Would like to see this for other coins, but a good amount of monero users will NOT use a remote node.
> 
> Also, there are _no_ monero wallets in f-droid official repo. I think it's important that we have one, and would be nice for unstoppable to be the first.

https://f-droid.monerujo.io/

**Comment by nahuhh** [comment]
> > Also, there are _no_ monero wallets in f-droid official repo. I think it's important that we have one, and would be nice for unstoppable to be the first.
> 
> https://f-droid.monerujo.io/

I repeat:
there are _no_ monero wallets in f-droid **official** repo.

**Comment by nahuhh** [comment]
> Found one on izzyondroid: https://github.com/WooKeyWallet/monero-wallet-android-app
> 
> * I do not endorse this project in any way, i just found it on aurora droid and hopefully it might help the developers.

Lol. Hard pass!

Not updates for 2 years, get one small update and now its being shilled by an account with private activity.

**Comment by esengulov** [comment]
@fusionneur @nahuhh @kdejaeger @hexchills @pjakma we looked into this and intended to add it in the next sprint but upon further inspection we decided to postone it due to following reasons:

- no SPV implmntation for it just yet. Adding this via RPC would include significant effort on our end as BTC like chains implemented in Unstoppable are all SPV neabled

- adding ability to work via custom node would inlude additional UI screens as well as there are some security concerns with user having to keep words on his own server. Not  big deal this one though consdering Monero users are likely to be tech savvy.

POstonin for another sprint would give us ability to study options a bit further. Hang in there please

**Comment by nahuhh** [comment]
> - no SPV implmntation for it just yet. Adding this via RPC would include significant effort on our end as BTC like chains implemented in Unstoppable are all SPV enabled
> 

Typical SPV will never be available for Monero, as Monero is not like other chains.
We have Mymonero and LWS. Neither is official.

> there are some security concerns with user having to keep words on his own server. 
These concerns are only an issue with "SPV-like" (mymonero and lws) services. 
Both force the user to give up view keys to the backend.

Full node wallets dont require storing anything with the remote node.

> - adding ability to work via custom node would inlude additional UI screens as well as 

; ). Using current method (scanning a bunch of nodes) is an attack vector. 
Instead of x amount of ransom nodes, jt should be 1 node only and this node and ip should be set by the user.

> Postponing for another sprint would give us ability to study options a bit further. Hang in there please

There would be a few more ui issues to look into, suck as monerod subaddresses / additional address screens.


Any full monero wallet starts with building the stock wallet api and making rpc calls on it.

SPV / LWS / Mymonero = no thanks

**Comment by esengulov** [comment]
Ok, let me digest this with the team and see what can be done. The 0.27 is intended to be a short sprint so we are likely to have this one done in 0.28🙏🏻😉

**Comment by candroid-man** [comment]
Looking forward to the update!

**Comment by TheFuzzStone** [comment]
@esengulov, cool. Then we are waiting for the next release.

All proprietary wallets that support Monero are all fucked up because they haven't updated their hard-coded Monero nodes. So, in your implementation of Monero be sure to give users freedom to choose which remote node to connect to. If one node is not updated in the future, the user will simply connect to another and have access to their XMR.

Also, give users freedom in the form of the ability to view/export private keys/mnemonic phrase of 25 words from Monero "account". That way, if something happens with Unstoppable Wallet, the user can import the private keys/mnemonic phrase into the official Monero CLI/GUI wallet.

**Comment by mvozzo** [comment]
I fully support @TheFuzzStone's comment above.  

In addition to adding Monero (which I think is highest priority) may I suggest you also consider adding Wownero (which is a hard fork of Monero) which has a slower emission schedule and is ASIC resistant Solo mining only (thus pool mining resistant).

Please allow for the same features as mentioned by TheFuzzStone, being, allowing Wownero users of Unstoppable Wallet the freedom to specify the remote node they wish to connect to. 

Hence, the work your dev teams put into Monero, can be quickly replicated to support Wownero. 

To learn more about Wownero:
Homepage - https://wownero.org
Talk to Devs - https://forum.wownero.com/

Thanks.

**Comment by nahuhh** [comment]
Adding wownero after monero should be a lot less painful / easy. WOW is an almost identical fork.
Nodes, RPC etc, same calls and functions.
Decimal place for wow is moved one to the right.

**Comment by kdejaeger** [comment]
Just wanted to say mixin wallet is open source and also has support for monero.

**Comment by esengulov** [comment]
closing due to the duplicate issue, https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5492

**Comment by esengulov** [comment]
> Is there any update about Monero (XMR) adoption in UW? A bookmark for this work? 0.36? 0.37?
thanks, we will give a try in 0.37. First will research and if feasible than implement it.

**Comment by esengulov** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5492
