### ISSUE TITLE
Ethereumkit returns a non-existent Transaction Hash.

### ISSUE THREAD

**Issue by eggham0518** [horizontalsystems/unstoppable-wallet-android#3323]
First of all, thank you for this library.

But there is a problem.
It succeeded in canceling the transaction by sending 0 back to itself for an ongoing transaction, but Ethereum Kit returns the wrong transaction.

![image](https://user-images.githubusercontent.com/45938450/109931567-5be8e000-7d0c-11eb-83e9-28b7428c1fc3.png)

https://ropsten.etherscan.io/address/0x9E5FFCd8543A48a3DB71a8808C396563f2f35c46

Always returns nonexistent Transaction Hash **0x80dfd521914a734d9794ecea1383c3f7b438ae307f1c08f79e4c2397a615**
And It does not return the BlockHeight of canceled transactions and transactions sent to zero.

When the application's data was deleted and the app was restarted, it was able to receive transaction details that matched Etherscan.

I think cached data doesn't change to new data, so please solve this problem.

**Comment by eggham0518** [comment]
If there is any change in the code, please share it with us.

**Comment by omurovch** [comment]
Hi @eggham0518,
Thank you for such detailed explanation. Can you please tell which version of EthereumKit, i.e. commit hash, you are using?

**Comment by eggham0518** [comment]
Because of minsdk version, about 3 weeks ago, we added Ethereum Kit project directly. I don't know the exact commit hash.

So I tested it with Ethereum kit (72c74ff) used in this project, and fortunately, I got a proper transaction list for the value sent to zero, but there is still a transaction hash that disappeared from the EtherScan.

There is the same problem as above when transactions occur by raising gas costs by 15% with the same nonce as previous transactions.

**Comment by omurovch** [comment]
AFAIU, your previously sent transaction, that is not included in block, is replaced with another transaction with the same nonce. EthereumKit stores such transactions and gives it back with the hash of the new transaction which replaced it, so that you can show dropped transactions too. But EtherScan deletes such dropped transactions. 
Please confirm that such dropped transaction is returned from ethereumKit with non-null droppedTransaction field. If it is the case, then this is expected behavior.

**Comment by eggham0518** [comment]
The problem was solved temporarily by filtering the transaction list without the same nonce value. I'll let you know if there's a problem. Thank you.
