### ISSUE TITLE
Receive redesign

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#3802]
![image](https://user-images.githubusercontent.com/42367908/120479101-5ebca500-c3cf-11eb-80f3-f0277682250c.png)

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=35878%3A317138

**Comment by TalgatNurdinov** [comment]
- [ ] Need to fix the paddings around QR code
- [ ] Dismissing snacker with a tap to empty space

-[ ] Also, please change the text close non the top to icon **X**

**Comment by abdrasulov** [comment]
@TalgatNurdinov dismissing snackbar on outside click requires custom implementation. The solution based on the activity. Since we are using fragments it may take a considerable amount of time. So my suggestion is to leave it as is.

P.S. user can dismiss snackbar with swiping it. it is the standard behavior out of the box.
