### ISSUE TITLE
Check Zecwallet’s BlazeSync

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#3839]
https://forum.zcashcommunity.com/t/zecwallets-blazesync-sync-entire-chain-in-60s/39447

**Comment by gmale** [comment]
FYI: we've been in communication with Aditya on this feature as he's built it and made changes to lightwalletd to support it (like streaming blocks in reverse to find notes faster).

We will need to circle back and figure out the best way to share this code so that the whole ecosystem can benefit. I'll keep you posted on any updates.

**Comment by esengulov** [comment]
Issue Merged Into https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3900
