### ISSUE TITLE
integrate Monero

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#3918]

**Comment by abdrasulov** [comment]
Hello @AbakumovAlexandr. Thanks for being willing to contribute to our project!

Adding support for a new coin requires changes in several places of the app. Also, the kits like the market-kit should support it too. So let's try to do it in small steps.

As the first step, you can start with IAdapter, IBalanceAdapter, and IReceiveAdapter interfaces. We need implementations of these interfaces for Monero.

**Comment by esengulov** [comment]
Duplicate of https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3302

**Comment by nahuhh** [comment]
> Hello @AbakumovAlexandr. Thanks for being willing to contribute to our project!
> 
> Adding support for a new coin requires changes in several places of the app. Also, the kits like the market-kit should support it too. So let's try to do it in small steps.
> 
> As the first step, you can start with IAdapter, IBalanceAdapter, and IReceiveAdapter interfaces. We need implementations of these interfaces for Monero.

Can you point me towards the relevant sections of code that need to be modified / created? I likely wont be able to get it done.. but maybe I can. 

This wallet needs monero. Its my fav multiwallet.. but it doesnt get used.. because I only use monero!  (Monero users actually use/spend monero. Even during a bear market)
