### ISSUE TITLE
BEP20  Gas fee seems to be not calculating

### ISSUE THREAD

**Issue by Kasun-thilina** [horizontalsystems/unstoppable-wallet-android#4056]
I tried to swap back this bep20 coin to BSC but it always keeps getting an error as "Current BNB balance is below amount required", Even though I got around 15$ in BNB. the gas fees are stated as "N/A" . Seems like the gas fee is not calculating. I tried setting the tolerance up to 12% as well. 

see the attached image : [https://imgur.com/a/aopjMAx](https://imgur.com/a/aopjMAx)

**Comment by esengulov** [comment]
@Kasun-thilina following on the problem)

So, after some research it turns out that issue mainly due to the specifics of Dexioprotocol token smart contract. As a result the client is unable to estimate the correct fee for the transactions. You still should be able to swap this token (via walletconnect) using Pancake v1 DEX protocol.

- https://docs.pancakeswap.finance/help/troubleshooting#estimategas-failed
- https://bscscan.com/token/0x29b1e39a529d3b3cacea55989594f71813e998bb#readContract
