### ISSUE TITLE
Keystore implementation in app has multiple bugs

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/unstoppable-wallet-android#4163]
1. On app launch ask for screen unlock. On unlock shows again same warning for screen unlock. Only phone restart helps with this issue.
2. On Samsung phone when phone dies due to low battery, keystore becomes invalidated. 

Related
1. #4447
2. #4884

**Comment by arkadym** [comment]
Could anyone help ? I'm using Fold 3 and today faced that issue, app is installed inside the knox, the problem is - even reinstall inside knox is not help, when i run app it shows same screen! Is there any file or folder i should delete ?

**Comment by abdrasulov** [comment]
Hello @arkadym, usually reinstalling the app should be enough. We could not reproduce the issue both inside and outside of Knox. Can you please check it outside of Knox? Also restarting the phone helped in some cases.

**Comment by arkadym** [comment]
> Hello @arkadym, usually reinstalling the app should be enough. We could not reproduce the issue both inside and outside of Knox. Can you please check it outside of Knox? Also restarting the phone helped in some cases.

Hello @abdrasulov, finally managed to solve by reboot device and reinstall. But is just very confusing, when you uninstall and install app again and it keep show same error...

As of install out of knox, i understand there could be issues supporting it, but why i have to avoid using knox, when it is designed exactly to secure sensitive data ? I thought Unstoppable developed for that also :) ?

I'm developer and know that knox has some differences in behavior comparing to main Android system, so issue itself is not something unusual. Just need to make app bit more user friendly and handle such scenario gracefully, I'm ok if somehow keystore become broken, it is one of possible real life scenarios, virus hacked my phone or anything... why not app show me that popup with Clear button , then just clean all it's data and start from welcome screen ? Because anyway i dont have any other way to fix it.

**Comment by abdrasulov** [comment]
@arkadym, you don't have to avoid using Knox. The app should work inside of Knox as well as outside of it. Since we could not reproduce the issue we need to figure out why it's not working on your device. Asking you to install it outside of Knox, we would like to understand if Knox is the reason for this issue. We will debug it further. Any additional information is welcomed.

**Comment by abdrasulov** [comment]
Could not reproduce the issue. Added the logging of key invalidated exceptions into the app log. This should help us to investigate the issue if it occurs in a user device.

**Comment by arkadym** [comment]
> Could not reproduce the issue. Added the logging of key invalidated exceptions into the app log. This should help us to investigate the issue if it occurs in a user device.

Is there new build with logging ? I mean i switched to use Unstoppable outside of Knox, and from the time i reported issue - it works fine (outside of Knox folder). I'm not happy but have no choice, i tried 3 times and all 3 times it tooks approx 2 days before it breaks...
If i could help investigate - tell me what to do.

**Comment by abdrasulov** [comment]
@arkadym, 

Thanks for your willingness to help! We are planning to publish the next release version in 1-2 weeks.

**Comment by arkadym** [comment]
Just installed 0.26 into knox folder, and after 1 day same issue happened - got popup telling lockscreen code changed. So still cannot use inside Knox folder.

**Comment by junzhli** [comment]
I am thinking if I am troubled with the same issue #5515  with yours @rafaelekol 
@abdrasulov you may try to reproduce the bug by the following steps:
Restore wallet with 12 words or 24 words with optional passphrase and wait it for restoration.
Top up some funds in the wallet and wait for at least 1-2 days, the keystore will invalidate itself without reason.
The reason I come up with the above steps is because I can't reproduce the problem if I just created a wallet without no fund in that wallet. Top up some funds may help

**Comment by abdrasulov** [comment]
Hello @junzhli,

Thanks for the detailed explanations. We also could not reproduce this issue before. We'll check that scenario.
