### ISSUE TITLE
Send Form: When going  to the address field and then back to the amount field - the keyboard closes (or does not open at all)

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#4462]

**Comment by esen** [comment]
This bug exists because `SendEvmFragment` uses "non-Compose" `FragmentSendEvmBinding` and "Compose" `HSAddressInput` view. `HSAddressInput` hides the keyboard on focus loss, because it doesn't see AmountInputView gaining focus.

The same bug exists in `OneInchSettingsFragment`. 

The solution would be to rewrite `FragmentSendEvmBinding` and `FragmentSwapSettings1inchBinding` using Compose framework
