### ISSUE TITLE
Suggestion: enable "discussions" on the repo and leave issues for bug reporting

### ISSUE THREAD

**Issue by ezxpro** [horizontalsystems/unstoppable-wallet-android#4811]
Just a suggestion. I first saw it here: https://github.com/valinet/ExplorerPatcher/issues/56

Now here too: https://dzhavat.github.io/2020/04/04/my-thoughts-on-github-discussions.html

This is a repo where they reserved "Issues" strictly to reporting bugs and discussing issue.

 It's common to have general questions among issues in any repo, so, maybe you guys find it interesting.

**Comment by pyrates999** [comment]
Unfortunately not even discussions now has the ability to make suggestions for new features as it's also been locked.

**Comment by sayore** [comment]
The latest Windows 11 makes Explorer Patcher crash into a loop, killing it is nearly impossible for normal users since it restarts by itself. 
Needing to open a cmd to uninstall, making them soft bricked.
Running on German Version - 22621.1344 - 22H2 - Windows 11 Pro - Windows Feature Experience Pack 1000.22639.1000.0

**Comment by sayore** [comment]
Wait this isnt even on the Patcher github
im blind
