### ISSUE TITLE
Add support C-chain 

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#4896]

**Comment by esen** [comment]
Made some research and tried to add Avalanche C-chain to the app. 

- Support of C-Chain can be added using **snowtrace.io** and **api.avax.network** APIs. 
- 1Inch supports C-Chain, so it has to be simple enough to add it.
- Haven't seen an exact copy of Uniswap. There's a **traderjoexyz.com** which looks like a copy of Uniswap, but it has some different method names like ("_swapExactAVAXForTokens_" instead of "_swapExactETHForTokens_"). That's why we'll need some more work to integrate TraderJoe
- **Blocking**: AVAX native coin and tokens must have different "_type_" field on backend.

**Comment by esen** [comment]
Atomic transactions on C-Chain (cross-chain transactions between X and C chains) are not reflected on standard transactions list coming from the explorer. So, we don't need to handle those txs. There may be inconsistencies between the balance and the coin transfers on the list of transactions, but this is not a problem since the balance and transactions are completely independent features.
