### ISSUE TITLE
Suggestion: App lockout timer

### ISSUE THREAD

**Issue by ezxpro** [horizontalsystems/unstoppable-wallet-android#4955]
I think it would be nice if the app didn't lock immediately every time I minimize it. Maybe there should be a timer or something.
This becomes a problem when switching back and forth with another app (e.g Binance), because as soon as I minimize the app, I get back to it, and I have to type the whole PIN again.

**Comment by ezxpro** [comment]
Wow, you guys are incredible 🎉🎉

**Comment by omurovch** [comment]
Hi @ezxpro,

Thank you for all your constructive feedbacks. 

Regarding this lock issue, the wallet is being locked in 3 cases:
- 60 seconds after going to background
- closing app using back button
- killing app (either from recents menu or by system)

The behavior, you were experiencing, is most probably due to app being killed in the background. We have made additional changes, so that it won't be killed in the background so often as before.

When pressing back button on the main page, should the wallet be closed and locked or just minimized and not locked? Which behavior do you expect?

**Comment by ezxpro** [comment]
Hi @omurovch 

Well, thanks for all the hard work, I really believe you're making a great app.
I also am glad that you appreciate the feedback!

>When pressing back button/gesture on the main page, should the wallet be closed and locked or just minimized and not locked? Which behavior do you expect?

In regards to this, it's a bit hard for me to answer this, for a couple of reasons. Those being:

1.  I didn't know pressing the back button kills the process, I'd never figure that out myself
2. Now that you said it, I see the I should be pressing the home button instead, most of the time the app will be unlocked if I switch back and forth
3. I use unstoppable inside a work profile, which gives me a different use case than most other users. It behaves differently, and for that reason, sometimes the app will be locked even if I use the home button, because the work profile locks itself (this is a standard, Android One feature), and thus the app will get locked too.

That being said, I think it would be nice to think about other users and what they would think about this type of behavior. Maybe most people know that the back button kills the process and will use the home button instead. Maybe they don't and it would be better to make both buttons minimize the app.

Honestly, I don't know what to say, I feel like I'm answering this on behalf of all Unstoppable users.

**Comment by omurovch** [comment]
Actually, pressing back button on the main page doesn't kill the app, it just closes main page and locks the wallet. App itself is alive and accessible via recents menu. It is similar to killing the app in that sense that it locks the wallet. 

The question now is which behavior is more expected, locking the wallet or not. In version 0.25, which will be available this week, pressing back button on the main page will lock the wallet. Maybe you should use for a while, and see if it is convenient.

Regarding locking when switching between apps, it works as expected. The behavior, you were experiencing, is most probably due to app being killed in the background. Please, see if the behavior still exists in version 0.25 and create an issue if it does. For now, we are closing the ticket.

**Comment by ezxpro** [comment]
Ok, is version 0.25 released already? I didn't see it here on GitHub.

**Comment by omurovch** [comment]
Today it will be released it on GitHub, and few days later on other platforms (Google Play, F-Droid).

**Comment by ezxpro** [comment]
@omurovch coming back to this on v0.25 now.

I did some testing, now i get your point about the back button. I think it should not lock the app when i press the back button. It becomes hassle pretty quickly.

When i oress the home button, though, it's not locking as often anymore 👍
