### ISSUE TITLE
Camera on notification is not gone after camera is closed

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/unstoppable-wallet-android#5456]
Camera on notification stays when user closes QR Scanner.

![photo_2022-10-17 16 40 29](https://user-images.githubusercontent.com/1390965/196157403-8f9829f2-7358-4227-a794-07026e6b89e8.jpeg)

**Comment by abdrasulov** [comment]
The reason is `CaptureManager::onDestroy()` is not called. With activity, it would be called in the appropriate method. But in AndroidView of compose, there is no way to do that. It's a known issue and discussed here https://twitter.com/lgancho/status/1573204033615134720. That should help. As of now, the ticket will be postponed
