### ISSUE TITLE
Wallet Connect: Add the ability to increase the gas limit (mainnet/testnet)

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#5598]

**Comment by omurovch** [comment]
Actually, this feature was requested mainly for testnet usage. The thing is, RPC provider, that we used, was wrongly estimating the gasLimit. As a result there was a need to increase gasLimit manually. But switching to another RPC provider solved the problem. So we are closing the issue for now.

Regarding "speeding up" Bitcoin transaction, actually there are some ways. For instance, if the tx has change output, it can be send back to your own address with higher fee. And most probably miners will include both transactions, because they will have aggregated higher fee. Or another way is to resend the same outputs with higher fee. But it could be viewed as "double spending". 
Since there are not much issues with Bitcoin stuck transactions for now, it was not in the agenda of the team.
