### ISSUE TITLE
Unlock the wallet without entering a pin: new concept idea

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#5632]
In my idea, of course, the pin remains usable in case of need.

The case I bring is another:

Unlock the wallet under a video surveillance device without revealing the pin.

It works like this:

Instead of reading the pin, the app unlocks itself when a certain previously established result is reached.

For example I tell Unstoppable Wallet that when it reads 100 as a result of a mathematical expression then it must open. Because you are supervised, you will need to establish at least 9-10 results that have value once. One access. Or if you want to make one fixed (at your need).

A few examples:

20 + 60 + 80 - 60 (enter) = 100 

45 + 45 + 40 - 30 (enter) = 100

-160 +60 +200 (enter) = 100

When the app reads 100 the wallet is opened.

Is it interesting or does it have any obvious gaps that I don’t see?

What can be added/removed to make this idea better?

It necessary to find a way to type + - × ÷ without showing the logical operators on the display. This is important in order not to reveal the result that unlock.
Also adding restrictions about the exact number of hops needed to unlock.

**Comment by esengulov** [comment]
:))) Thanks for the idea. The idea is certainly nice.... there may be some caveats that are not obvious on the first sight. As you have already noticed there are things like number of hops, input method, error handling logic etc. I would say one of the main issues here might be complexity of the UI that would make it clear to users what is that and how it needs to be configured.

At the moment we are designing one other feature you suggested (Duress PIN) and it turns out there are a lot of points to consider even fora such small feature :). We have just started working on the UI/UX side of it and if all goes well we will have it implemented.

thanks!
