### ISSUE TITLE
Do not display what are likely to be phishing/spoofing transactions in Transactions tab

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#5715]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5712

**Comment by esengulov** [comment]
As per our discussion it was agreed that all TRANSFER type transactions with 0 amount will be hidden.

**Comment by aleqx** [comment]
Please don't hide them entirely. Many of them are legitimate (e.g. cancelling a transaction is usually done with a 0 amount transaction, I will want to see those) while spoofing ones are of interest. I will want to know if my address is being targeted by poison attacks (maybe I want to get rid of that wallet, generate a new one).

What I suggested in #5712 was better in my opinion: Hide only the ones where 
- the user's wallet is not the *initiating* address (i.e. it's a smart contract executing `transferFrom()`),
- and which are 0 amount,
- and allow the user to reveal them if they want to (move them to a separate tab or a toggle button to reveal them).
- and do add a warning regardless (educating your users is very useful and they will appreciate you for thinking of their well being)

**Comment by ealymbaev** [comment]
@aleqx 

Let me explain in details. In our app we already had spam transaction filtering logic. It has the following rules:

- hide any transaction that was initiated by third party user/contract AND has `Transfer` log(s) associated with user address AND transferred token is not in our Market list (some kind of whitelist)

Sometimes user had a lot of (more than 10 in a row) spam transactions in his tx list and it was difficult to find non-spam transactions. That is why he had applied this spam filter.

As about spoofing transactions - we had added the following additional rules to our spam filter:

- hide any transaction that was initiated by third party user/contract AND has `Transfer` log(s) associated with user address AND transferred token is IN our Market list AND transferred value is 0.

Your case about cancelling transaction will not satisfy spam filter because it would be initiated by you. Revealing spoofing (as well as spam) transactions should be discussed and may be added in next releases @esengulov
