### ISSUE TITLE
Private key & transfer and swap Issue 

### ISSUE THREAD

**Issue by Esmail0karimi** [horizontalsystems/unstoppable-wallet-android#6634]
I created a wallet in unstoppable wallet but I find out seed pharse and privacy key show me as (00) Now just I have back up file unfortunately I can't restore my wallet to other wallet for example when i want to restore wallet in metamask i have error not a v3 wallet on the other hand when I want to transfer my asset in unstoppable wallet  I have error scalar is not in the interval [1 ,n-1]  Please help me to solve this Issue I need transfer my asset 
Thank you 🙏

![IMG-20230902-WA0005.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/91189643/30bf087e-d23f-4cbe-ae1f-ead127fc94f1)

![IMG_20230920_085850_391.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/91189643/887c3aed-06fb-4f53-b44e-674e17dc8f3b)

![IMG_20230904_081529_312.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/91189643/6f826129-3883-4e88-bc21-e71c15c13808)

**Comment by Dianaaiym** [comment]
After reviewing your concern, we have determined that the issue you are experiencing is not related to the technical aspects of our wallet. Here's why:

1. **Creation and Restoration Date**: You mentioned creating your wallet in 2018 and making a backup in Unstoppable at that time. However, backups for Unstoppable Wallet were only available starting from June 27, 2023. Claims of backups created before that date are not valid.

2. **Similar Requests**: We have received numerous similar requests from users worldwide in 2023, all reporting the same issue and ETH address as yours. This suggests that the problem may not be unique to your situation and is not caused by a technical flaw in our wallet.

3. **Explanation of Error "scalar is not in the interval [1, n-1]"**: This particular error, "scalar is not in the interval [1, n-1]," is typically encountered when attempting to send or swap funds from a "watch wallet." A "watch wallet" is a wallet that has not been restored using a seed phrase, private key, or backup file but is merely being monitored. We suspect that your custom-built APK might be the source of this error, as it appears to have features that extend beyond the capabilities of a standard watch wallet.

In conclusion, we regret to inform you that we will not be able to provide further assistance or engage in communication regarding this matter. Additionally, we will not entertain similar inquiries from individuals reporting the same error and using the same ETH address. Thank you for your understanding.
