### ISSUE TITLE
Why Close my issue without solve it 

### ISSUE THREAD

**Issue by Esmail0karimi** [horizontalsystems/unstoppable-wallet-android#6690]
Hi @Dianaaiym  why try to close my issue by slandering me this is my wallet and I have my back up file and password
Is there a wallet without backup system ?? How you can tell me your app don't support backup file just you can tell restore back file is start of 2023 
The details of my backup proof me I created wallet in unstoppable wallet and get backup 
Your app had problem and destroyed my backup file and now I find out ciphertext in My backup is small Than standard ciphertext and this is your app issue when I getting backup 
I trusted your app and invest my ethereum on your app but now you can't solve my problem and close my issue without solve it 
Its very obvious that don't care damn to your customer and their investment and money

**Comment by Dianaaiym** [comment]
<img width="370" alt="Screenshot 2023-10-04 at 13 08 52" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/49d58385-7957-4a82-acb9-086c7b6fceb4">
https://github.com/horizontalsystems/unstoppable-wallet-android/releases/tag/0.33.0

We are always ready to assist and support our users. However, after conducting the necessary checks, we regret to inform you that we are currently unable to provide technical support for your account. This is due to inconsistencies in your statements. You mentioned creating a wallet in Unstoppable Wallet in 2018 and making a wallet backup a year ago. However, it should be noted that Unstoppable was released in 2019, and the wallet backup feature was only introduced a few months ago.

Thank you for your understanding.

**Comment by Esmail0karimi** [comment]
> The non-custodial approach requires great responsibility and some field knowledge.
> 
> You claim to have invested money in cryptocurrencies. Dry question: Did you save the seed? 
> 
> No? Go back to the banking system where your money is kept by people who think and decide for you.
> 
> That’s the right approach for you because if you haven’t saved the seed, it’s all your fault.
> 
> The End

So don't need other option backup file and privacy key 
Why set it in application just for build beautiful wallet or useful wallet ???
