### ISSUE TITLE
The master pin leads to a secret screen

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6808]
The master pin leads to a secret screen, not to wallets. At least not right away.

On this screen the user can open previously created wallets' groups or add a new group.
Each group of wallets can be associated with a dedicated pin and name.
One can add as many wallets' groups as it wants.

This screen is only accessible by typing the master pin. It is something like the emergency mode of Windows, when one starts the operating system in recovery mode.

This screen is not shown, nor is it accessible via other pins.

No longer need of a visible duress pin option in Settings. Just one have to access to the secret screen and then add a new group with the chosen "duress" wallet and its associated pin. End.

**Comment by abdrasulov** [comment]
There should not be a UI/UX difference between the master and duress pin. The reason is that when a user opens the app with a Duress pin no one should be able to guess that the opened account is not master. 

Imagine there is some bad guy who knows how the Duress pin feature works. And he asks some other person to show his balance in the app. So if there is a difference between master and duress modes the bad guy will be able to guess that the app is opened in duress mode. That is why we have a requirement there should not be any difference between UI/UX for master/duress modes.
