### ISSUE TITLE
Sometime "random" is not truly random (numpad)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6934]
By software is it possible adding an extra rule?
--> a number never can't get its own position.

To avoid the right number in its proper position.

![1000102242](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/9da88ae4-fd7a-45a0-a490-cdcea1ee28b3)

![1000102244](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/e8d9ad89-f3fa-4b72-94bf-1a2522be7f61)

![1000102246](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/2bc60d7e-5212-4ac5-b379-2e5b1ccd1f2b)

**Comment by NateNate60** [comment]
That's not a bug. That's intentional and a good feature. Otherwise, if someone sees you pressing the button where 0 usually is, then they immediately know that digit of the passcode isn't zero. Not allowing a digit to map to itself leaks information about what that digit is.

Famously, the thinking that a random mapping should never allow a digit to map to itself was one of the design flaws exploited by the Allied Powers in World War II to crack the Enigma, a German encryption machine.

Allowing digits to map to themselves improves security.

**Comment by notpri** [comment]
It is random and that is a good feature. Those 2 or 3 numbers at the correct position never compromise the security.
