### ISSUE TITLE
Notifications | in-app alerts

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6940]
I would like to receive a notification (in the drawer and in device lock screen) when an ingoing transaction hits any of my crypto addresses.

This is especially useful when one wait for a payment and it happens over night. So when one wake up the next morning can see the payment notification.

**Comment by notpri** [comment]
@abdrasulov Please do not add this feature as it will require UW to track IP addresses and transactions to deliver notifications. Please stick to your privacy and anonymity promises of UW. The privacy and anonymity UW offers us are the reasons we use UW. If there are changes in it, we will move on. @serrq for the notifications to deliver to you, UW will then need to keep track of your IP address to deliver you notification of a transaction, keep track of your assets to know what asset you just received and also at what time you received it and what coin and how much that is and from whome it is. So please you better close this issue and next time please first think about privacy and anonymity. Also you can close this issue as UW is not meant for it. You also dont need notifications as you know when are you going to receive an asset and you look for it so  again this issue is a problem than a suggestion.

**Comment by abdrasulov** [comment]
@serrq @notpri,

Hi folks,

We appreciate all of our users. Especially, those who give feedback. 

We agree with both of you. It is a good feature to have notifications for incoming transactions and balance updates. One possible solution is to track user transactions on the backend and send them notifications. But this is not privacy-friendly. 

Another possible solution is to periodically check for new transactions in the app in the background. But it may not work for Bitcoin-based blockchains, since they need more time for syncing and OS may block app background tasks.

Let's leave this issue open for now. Once we have a good solution we'll get back to it.
