### ISSUE TITLE
Remove new send/receive/swap button from balance screen

### ISSUE THREAD

**Issue by r4v3r23** [horizontalsystems/unstoppable-wallet-android#6983]
Hi, please add an option to remove the recently added buttons under the balance and go back to old UI. all those buttons arae already available once i select the coin i want to send, theres no reason to have it on main screen

**Comment by notpri** [comment]
Yes, I also dont like this button. @abdrasulov @rafaelekol . You can remove these buttons from balance screen as we never use them. We already have those buttons when we click on an asset. now wha you can is :
1. Replace these buttons with "Add Token" and remove that Icon because thats confusing for newbies. 
2. Add a tab/section with name "Exchange" or "Swap".

**Comment by Dianaaiym** [comment]
There is an option to disable these buttons. Please check version 0.39
