### ISSUE TITLE
Allow speed-up and cancel for Bitcoin transactions

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6987]
- [ ] Add an option to enable/disable RBF (Replace-by-Fee) in the "Advanced Settings" section.
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=70724-464696&mode=design&t=VK4IbEmDiWyeZGZ7-0

- [ ] If the user has disabled RBF, display a notification when sending a transaction, informing them that RBF is disabled.
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=65645-308453&mode=design&t=VYqqj0ODkJjbLA53-0

- [ ]

**Comment by abdrasulov** [comment]
#6943

**Comment by omurovch** [comment]
> What if for some reason a merchant doesn't allow for a RBF transaction? UW automatically switch for opt-out RBF and send a standard one?

In send advanced settings there will be a switcher for opt-out RBF, by default it will be ON. If merchant doesn't allow RBF user should turn it off when sending.

**Comment by omurovch** [comment]
RBF is considered an advanced setting, and for most users, it may be unclear or even confusing in the Send screen. The main reason for adding RBF support was to enable the speed up or cancellation of stuck transactions. That's why the decision was made to have it ON by default.

If a merchant refuses an RBF transaction, it will still be approved in approximately 10 minutes, and the process won't differ from other non-RBF transactions. Users can choose to turn off RBF for their next transaction. Can you name a few such services/merchants that accept BTC payments and disallow RBF?


> Isn’t it better to place the switch in the send screen? Many people will not understand what happens (if the merchant refuses RBF): having the RBF on/off button on the same screen could facilitate understanding. In my opinion.
