### ISSUE TITLE
What's happening with Ethereum network? Maintenance works in progress?

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7056]
![1000105944](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/019e8fd7-5baf-4f2a-98f2-c72da4da093d)

**Comment by Dianaaiym** [comment]
> It seems working properly again. Just I wait the technicians' opinion and I close the issue in about 3 hours if situation is solved definitively.

Hello,

We sincerely apologize for the inconvenience caused by exceeding the daily query limit on Infura.

Rest assured, we've taken steps to address this issue.

In case you encounter a similar situation in the future or simply prefer to use an alternative source, you can always switch to LlamaNodes within our app.
