### ISSUE TITLE
Duress mode issues with hiding wallets

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7124]
Steps:
1. install UW
2. create a wallet (wallet 1)
3. go to settings
4. create a passocde for UW
5. create a new walllet (wallet 2)
6. Enable duress mode
7. select wallet 2 for duress mode
8. Now close the app and open again
9. enter simple passocode for UW (not the duress mode one)
10. you will see wallet 1 but just go to manage wallets and you will also see wallet 2 visible there which should be hidden since we enable it for duress mode.
11. now close the UW again and open again
12. Now enter duress mode passcode
13. go manage wallets and you will see only the wallet 2  which we selected for duress mode (wallet 1 which was not setup for duress mode is hidden) which is good but upon entering the passocde for wallet 1 , the wallet 2 (duress mode wallet) is also visible.
14. FIX hiding the wallet 2 (duress mode wallet) when entering passcode for wallet1 (simple UW) passcode.

**Comment by notpri** [comment]
![Screenshot_2024-02-26-08-16-11-96](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/93fe6679-dbe7-4056-9f05-5f9ce1cd50b3)

**Comment by notpri** [comment]
The wallet 1 which not a duress mode wallet is hidden when entered the passcode for duress mode wallet 2 but wallet 2 which is a duress mode wallet is not hidden when entered passcode for wallet 1.

**Comment by ealymbaev** [comment]
Let me explain behavior of the Duress Mode feature:

- all duress mode passcodes have their own "level"s
- master passcode (first passcode) has level 0
- if you set duress passcode from level 0 - it will create duress passcode with level 1
- if you enter app using level 1 passcode and create another duress passcode - it will create level 2 passcode and so on
- thus all wallets created in the app also have their own "level"s (that equals to passcode level). In another words if you enter the app using level 2 passcode and create a wallet - this newly created wallet will have level 2 as well.
- any passcode has access to its own level wallets + all higher level wallets

Thus `level 0` passcode has access to ALL wallets, `level 1` passcode has access to wallets with levels higher than 1 and so on.

Also you should know that biometrics (if enabled) always opens the highest level passcode.

All this behavior is made intentionally, because intruder should not identify that currently entered passcode is duress one.

**Comment by notpri** [comment]
ok
