### ISSUE TITLE
What is the criteria behind this choice?

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7589]
UW 0.39

Last 3 months -260% is strong buy in my opinion.

Buy at lowest, sell at highest. There is no other interpretation.

![1000113997](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/f5e88831-07e1-47a0-bfc2-5da646247245)

**Comment by ant013** [comment]
![IMG_1732](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/13083244/893f22a3-2d37-42b5-837d-d453e5dce3be)
We use daily candles to determine the current trend and possible market reversal. The main indicator is the Bollinger Band, which shows the moments when an asset goes beyond the default price deviation. Since during strong movements this can happen several times in a row, we need to use filters to filter out false signals. The only filter we currently use is the RSI. It shows when the market is overbought or oversold. Accordingly, if the market is oversold and the asset sharply moves out of the BB zone, then with a certain degree of confidence we can say that it has reached a local bottom upon returning to the zone. Of course, such an analysis cannot cover cases where the news background forces the asset to fall even further. It is not uncommon for the asset to repeat the fall and exit the BB zone after returning to it, and sometimes this can happen 2-3 times, but with emerging divergences on the RSI and MACD indicators.

Using this token as an example, we can see that it went beyond the BB zone with the body of the candle (purple color), but it was not oversold at that time. It became oversold a week later, however, it was not able to break through the BB zone with a strong move. In this form, we can assume with a high probability that there may be another drop with the body fixing below the BB and returning back. Of course, each of the indicators separately gave a signal for a possible trend change, there was no point where they would coincide.

**Comment by ant013** [comment]
In simple terms, if the price is falling steadily, without sudden jumps, then there are no buy signals. Signals appear when the price really breaks out of the "normal" decline, which happened with some other tokens (APT, SEI, OP).
