### ISSUE TITLE
Two new stablecoins are MiCA compliant in EEA: please add them

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7625]
MiCA is the latest regulation pack issued by European Commission about crypto and stablecoins. Currently the only stablecoins that fits MiCA compliance are:

• USDC, EURC issued by Circle LLC (French license)
• EUROe, eUSD issued by Membrane Finance Oy (Finnish license)

`EUROe` is available on these chains (verify by yourself):

https://dev.euroe.com/docs/Stablecoin/contract-addresses

• Ethereum
0x820802Fa8a99901F52e39acD21177b0BE6EE2974

• Avalanche
0x820802Fa8a99901F52e39acD21177b0BE6EE2974

• Polygon
0x820802Fa8a99901F52e39acD21177b0BE6EE2974

• Arbitrum
0xcF985abA4647a432E60efcEeB8054BBd64244305

• Solana
2VhjJ9WxaGC3EZFwJG9BDUs9KxKCAjQY4vgd1qxgYWVg

• Optimism
0x820802Fa8a99901F52e39acD21177b0BE6EE2974

`eUSD`

https://dev.emtusd.com/docs/Stablecoin/contract-addresses

• Ethereum
0x03EA574de701110FA898C774B5D2D7Feb6e23bC2

**Comment by Dianaaiym** [comment]
> MiCA is the latest regulation pack issued by European Commission about crypto and stablecoins. Currently the only stablecoins that fits MiCA compliance are:
> 
> • USDC, EURC issued by Circle LLC (French license) • EUROe, eUSD issued by Membrane Finance Oy (Finnish license)
> 
> `EUROe` is available on these chains (verify by yourself):
> 
> https://dev.euroe.com/docs/Stablecoin/contract-addresses
> 
> • Ethereum 0x820802Fa8a99901F52e39acD21177b0BE6EE2974
> 
> • Avalanche 0x820802Fa8a99901F52e39acD21177b0BE6EE2974
> 
> • Polygon 0x820802Fa8a99901F52e39acD21177b0BE6EE2974
> 
> • Arbitrum 0xcF985abA4647a432E60efcEeB8054BBd64244305
> 
> • Solana 2VhjJ9WxaGC3EZFwJG9BDUs9KxKCAjQY4vgd1qxgYWVg
> 
> • Optimism 0x820802Fa8a99901F52e39acD21177b0BE6EE2974
> 
> `eUSD`
> 
> https://dev.emtusd.com/docs/Stablecoin/contract-addresses
> 
> • Ethereum 0x03EA574de701110FA898C774B5D2D7Feb6e23bC2

Thank you for sharing information about the EUROe and eUSD stablecoins. We appreciate your interest in adding these tokens to our platform. However, we have certain criteria for adding new tokens, which include:

Minimum 24-hour trading volume: $200,000
Minimum 24-hour trading volume for trusted tokens: $500,000
Minimum market capitalization: $10,000,000

At this moment, we cannot add these tokens because they do not meet our criteria. However, if you'd like to use these tokens, you can use our "Add custom token" feature.
