### ISSUE TITLE
Research : IPFS Light Client Implementation on Kotlin/Java

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#829]
Research Kotlin implementation for https://github.com/ipfs/go-ipfs

The goal here is to enable every mobile client (in our case wallet) to be able to write /read data directly from local IPFS server. In other words, instead of making requests to our remote IPFS Node the client needs to be able to communicate with IPFS directly from locally node. As per our estimates this should significantly increase the speed.

Before getting on the task organize a meeting with @abdrasulov @ealymbaev @uberkerim @nk-the-crazy

**Comment by nk-the-crazy** [comment]
After doing some research, I found that ARM binary dist. of the IPFS can be run on Android. No need for building IPFS GO-source with gomobile tools (https://github.com/golang/go/wiki/Mobile).
But we definitely should test both versions to review performance changes.

**Comment by rafaelekol** [comment]
While playing with SweetIPFS, which has good usage of IPFS on Android I found out that it download 4 binaries from IPFS distro. Then during IPFS setup it only uses only one, which current device can work with. Since all 4 binaries can add up to 52 mb to APK file, I started to search for way we can decrease this size.
Android has ability to build custom builds for each ABI(arm64,  amd64, 386). We just need to configure our app. Add needed binaries, Upload single APK to Play Store, and Google will generate apks for each ABI.
Links
https://developer.android.com/platform/technology/app-bundle
https://developer.android.com/studio/build/configure-apk-splits.html#configure-abi-split

**Comment by rafaelekol** [comment]
I managed to use IPFS in our to project to fetch exchange rates. Currently facing problems are:
- Fetched data most of the time is outdated. For example when I try to fetch rates with request like below it can give outdated data. But when I make request to direct node, it always gives latest data.
```
http://127.0.0.1:5001/api/v0/cat?arg=/ipns/QmXTJZBMMRmBbPun6HFt3tmb3tfYF2usLPxFoacL7G5uMX/xrates/latest/USD/index.json
https://ipfs-ext.horizontalsystems.xyz/ipns/QmXTJZBMMRmBbPun6HFt3tmb3tfYF2usLPxFoacL7G5uMX/xrates/latest/USD/index.json
```

**Comment by rafaelekol** [comment]
Issue on slow `swarm connect` in IPFS-GO project
https://github.com/ipfs/go-ipfs/issues/6303
